apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: ai-todo-py
build:
  artifacts:
  - image: my-taskapi
    context: backend
  - image: my-todo
    context: frontend
deploy:
  kubectl:
    manifests:
    - manifests/backend.yaml
    - manifests/frontend.yaml
    - manifests/mongo-pv.yaml
    - manifests/mongodb.yaml
