apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapi
  labels:
    app: taskapi
spec:
  selector:
    matchLabels:
      app: taskapi
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: taskapi
        tier: backend
    spec:
      containers:
      - name: taskapi
        image: my-taskapi
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_HOST
          value: mongodb
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: taskapi
  labels:
    app: taskapi
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: taskapi
    tier: backend

