apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
        tier: frontend
    spec:
      containers:
      - name: todo
        image: my-todo
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: TASK_API_HOST
          value: taskapi
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: todo
  labels:
    app: todo
    tier: frontend
spec:
  # type: NodePort
  # ports:
  # - port: 8081
  # selector:
  #   app: todo
  #   tier: frontend
  type: ClusterIP
  selector:
    app: todo
    tier: frontend
  ports:
  - port: 8081
    targetPort: http-server
