apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: db
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        ports:
        - name: mongodb
          containerPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim

---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
    tier: db
  name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
    tier: db